apiVersion: apps/v1
kind: Deployment
metadata:
  name: openjdk-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openjdk
  template:
    metadata:
      name: openjdk
      labels:
        app: openjdk
    containers:
    - name: openjdk-container
      image: fatimatabassum/fatima12:latest
      ports:
      - containerPort: 8080
