apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jivedh2019-assign
  template:
    metadata:
      name: jivedh2019
      labels:
        app: jivedh2019-assign
    spec:
      containers:
      - name: my-container
        image: jivedh2019/assign:IMAGE_TAG
        ports:
        - containerPort: 90
